name: Deploy to Firebase Hosting (PR)

on:
  pull_request:
    branches:
      - setup  # This triggers the workflow when a PR is created or updated against the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Set the Node.js version required for your app

    - name: Install dependencies
      run: |
        npm install

    - name: Build with Vite
      run: |
        npm run build  # Runs the Vite build process to generate the 'dist' folder

    - name: Deploy to Firebase (Preview Channel)
      uses: wzieba/Firebase-Deploy-Action@v0.2.0
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}  # Firebase token from GitHub secrets
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}  # Firebase Project ID in GitHub secrets
        channel: pr-${{ github.event.pull_request.number }}  # Creates a unique preview URL for the PR
