name: Deploy to Firebase Hosting (PR)

on:
  pull_request:
    branches:
      - setup  # This triggers the workflow when a PR is created or updated against the 'setup' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install

    - name: Build with Vite
      run: |
        npm run build  # Runs Vite build to generate the 'dist' folder

    - name: Deploy to Firebase (Preview Channel)
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
        channel: pr-${{ github.event.pull_request.number }}
