name: Deploy to Firebase Hosting on PR

on:
  push:
    branches:
      - main  # Trigger action on PRs targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the Node version required by your app

    - name: Install dependencies
      run: |
        npm install

    - name: Build with Vite
      run: |
        npm run build  # Runs Vite build to generate the 'dist' folder

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO0788 }}
        channelId: pr-${{ github.event.pull_request.number }}  # Unique channel for each PR
        projectId: portfolio0788
        entryPoint: .
